apiVersion: v1
kind: Pod
metadata:
  name: flox-containerd-demo
  annotations:
    # Required: the FloxHub environment to be activated within the pod
    flox.dev/environment: "flox/echoip"
    # Optional: disable Flox metrics reporting
    # flox.dev/disable-metrics: "false" # default
spec:
  # Required: directs containerd to use the Flox backend
  runtimeClassName: flox
  containers:
    - name: echoip
      # We provide `flox/empty` as a demonstration that the Flox
      # environment requires nothing from the container image.
      image: flox/empty:1.0.0
      # The command to run inside your environment
      command: ["echoip"]
